services:
  django:
    image: django_app
    container_name: django_app
    build:
      context: ./djangoApp
    ports:
      - "8000:8000"
    volumes:
      - ./djangoApp:/app
    command: >
      bash -c "./wait-for-it.sh mysql:3306 -- echo 'MySQL is up!' && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - mysql

  react:
    container_name: react_app
    image: react_app
    build:
      context: ./reac_view
    volumes:
      - ./react_view:/app
      - /app/node_modules
    ports:
      - "5173:5173"

  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=kevinalpizar1998@PUTOamo
      - MYSQL_DATABASE=default
    volumes:
      - django_react_data:/data/db
      - ./dumps:/docker-entrypoint-initdb.d:ro

volumes:
  django_react_data:
